version: '3.3'

services: 
  node:
    restart: always
    build: .
    env_file: .env
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
    depends_on: 
      - db
    volumes: 
      - .:/usr/src/app

  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node

  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$DATABASE
      - POSTGRES_USER=$USER_DB
      - POSTGRES_PASSWORD=$PASSWORD_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

volumes:  
  db_data: