version: '3.3'
services: 
  node:
    restart: always
    build: .
    env_file: .env
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
    # links: 
    #   - mongodb
    volumes: 
      - .:/usr/src/app

  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node